<?php

/**
 * OMNIPULSE Design Tokens — Auto-generated, do not edit.
 * Source: packages/tokens/src/tokens.json
 * Run: pnpm tokens:build
 */

return [
    'color_brand_graphite_mist' => '#40454D',
    'color_brand_golden_saffron' => '#F5C754',
    'color_brand_coral_blaze' => '#F55F52',
    'color_brand_fresh_meadow' => '#64BD79',
    'color_brand_aqua_sky' => '#6DB2CC',
    'color_neutral_white' => '#FFFFFF',
    'color_neutral_off_white' => '#F8F9FA',
    'color_neutral_border_light' => '#E2E4E8',
    'color_neutral_muted' => '#9CA3AF',
    'color_neutral_graphite_light' => '#5A5F67',
    'color_neutral_graphite_dark' => '#2F3338',
    'color_semantic_primary' => '#F5C754',
    'color_semantic_primary_foreground' => '#40454D',
    'color_semantic_secondary' => '#40454D',
    'color_semantic_secondary_foreground' => '#FFFFFF',
    'color_semantic_accent' => '#C7E0EA',
    'color_semantic_accent_foreground' => '#40454D',
    'color_semantic_destructive' => '#F55F52',
    'color_semantic_destructive_foreground' => '#FFFFFF',
    'color_semantic_success' => '#64BD79',
    'color_semantic_success_foreground' => '#FFFFFF',
    'color_semantic_background' => '#FAFAFA',
    'color_semantic_foreground' => '#40454D',
    'color_semantic_card' => '#FFFFFF',
    'color_semantic_card_foreground' => '#40454D',
    'color_semantic_muted' => '#F1F2F3',
    'color_semantic_muted_foreground' => '#6B7280',
    'color_semantic_border' => '#E2E4E8',
    'color_semantic_input' => '#E2E4E8',
    'color_semantic_ring' => '#F5C754',
    'color_chart_1' => '#F5C754',
    'color_chart_2' => '#40454D',
    'color_chart_3' => '#6DB2CC',
    'color_chart_4' => '#64BD79',
    'color_chart_5' => '#F55F52',
    'fontFamily_heading' => ["Montserrat","Arial","Helvetica","sans-serif"],
    'fontFamily_body' => ["Merriweather Sans","Open Sans","Arial","sans-serif"],
    'fontFamily_accent' => ["Caveat","Indie Flower","cursive"],
    'fontFamily_mono' => ["ui-monospace","SFMono-Regular","monospace"],
    'fontSize_xs' => '0.75rem',
    'fontSize_sm' => '0.875rem',
    'fontSize_base' => '1rem',
    'fontSize_lg' => '1.125rem',
    'fontSize_xl' => '1.25rem',
    'fontSize_2xl' => '1.5rem',
    'fontSize_3xl' => '1.875rem',
    'fontSize_4xl' => '2.25rem',
    'fontSize_5xl' => '3rem',
    'spacing_0' => '0',
    'spacing_1' => '0.25rem',
    'spacing_2' => '0.5rem',
    'spacing_3' => '0.75rem',
    'spacing_4' => '1rem',
    'spacing_5' => '1.25rem',
    'spacing_6' => '1.5rem',
    'spacing_8' => '2rem',
    'spacing_10' => '2.5rem',
    'spacing_12' => '3rem',
    'spacing_16' => '4rem',
    'spacing_20' => '5rem',
    'spacing_24' => '6rem',
    'spacing_base' => '0.25rem',
    'borderRadius_base' => '0.5rem',
    'borderRadius_sm' => 'calc(0.5rem - 4px)',
    'borderRadius_md' => 'calc(0.5rem - 2px)',
    'borderRadius_lg' => '0.5rem',
    'borderRadius_xl' => 'calc(0.5rem + 4px)',
    'borderRadius_full' => '9999px',
    'shadow_color' => '#40454D',
    'shadow_sm' => '0 1px 6px -1px rgba(64, 69, 77, 0.1)',
    'shadow_md' => '0 1px 6px -1px rgba(64, 69, 77, 0.1), 0 2px 4px -2px rgba(64, 69, 77, 0.1)',
    'shadow_lg' => '0 1px 6px -1px rgba(64, 69, 77, 0.1), 0 4px 6px -2px rgba(64, 69, 77, 0.1)',
];
